_________
# Import, label, and export the test data
_____________

In [16]:
import requests
import io
import pandas as pd
import numpy as np

# 1. import phenology dataset and select data

In [17]:
#import phenology (climate+daylength+observations) data from GitHub:Floydworks
url = ('https://raw.githubusercontent.com/Floydworks/WildflowerFinder_Phenology_Tool/main/cleaned_data_files/phenology_dataset_2017_2022_df.csv')
download = requests.get(url).content
# Read the downloaded content and turn it into a pandas dataframe
phenology_data = pd.read_csv(io.StringIO(download.decode('utf-8')))
print('phenology_data:', phenology_data.shape)

phenology_data: (37901, 39)

In [18]:
df_test = phenology_data[phenology_data['park']=='MtDiablo']
print(df_test.shape)
df_test

(19042, 39)

,id,park,plain_dates,Year,Month,Day,WY,wy_month,WY_weeknum,genus_species,...,AvgMinTemp_prior14,MaxDayLen_prior14,sum_prec_prior30,MaxTemp_prior30,MinTemp_prior30,AvgMaxTemp_prior30,AvgMinTemp_prior30,MaxDayLen_prior30,url,image_url
18859,104162921,MtDiablo,20220101,2022,1,1,2022,4,13,Quercus douglasii,...,35.265714,34511.0,8.358268e+00,73.94,28.94,50.402,38.288,34901.0,https://www.inaturalist.org/observations/10416...,https://inaturalist-open-data.s3.amazonaws.com...
18860,104162922,MtDiablo,20220101,2022,1,1,2022,4,13,Tauschia hartwegii,...,35.265714,34511.0,8.358268e+00,73.94,28.94,50.402,38.288,34901.0,https://www.inaturalist.org/observations/10416...,https://inaturalist-open-data.s3.amazonaws.com...
18861,104162923,MtDiablo,20220101,2022,1,1,2022,4,13,Boechera breweri,...,35.265714,34511.0,8.358268e+00,73.94,28.94,50.402,38.288,34901.0,https://www.inaturalist.org/observations/10416...,https://inaturalist-open-data.s3.amazonaws.com...
18862,104162927,MtDiablo,20220101,2022,1,1,2022,4,13,Ribes malvaceum,...,35.265714,34511.0,8.358268e+00,73.94,28.94,50.402,38.288,34901.0,https://www.inaturalist.org/observations/10416...,https://inaturalist-open-data.s3.amazonaws.com...
18863,104162931,MtDiablo,20220101,2022,1,1,2022,4,13,Dudleya cymosa,...,35.265714,34511.0,8.358268e+00,73.94,28.94,50.402,38.288,34901.0,https://www.inaturalist.org/observations/10416...,https://inaturalist-open-data.s3.amazonaws.com...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37896,105804701,MtDiablo,20220125,2022,1,25,2022,4,16,Arbutus menziesii,...,47.788571,36315.0,1.236220e+00,64.94,28.94,54.170,42.590,36315.0,https://www.inaturalist.org/observations/10580...,https://inaturalist-open-data.s3.amazonaws.com...
37897,124627543,MtDiablo,20220627,2022,6,27,2022,9,36,Arctostaphylos auriculata,...,59.925714,53242.0,3.937008e-02,91.04,42.08,77.336,57.668,53242.0,https://www.inaturalist.org/observations/12462...,https://static.inaturalist.org/photos/21125715...
37898,125825907,MtDiablo,20220711,2022,7,11,2022,10,38,Vitis californica,...,55.425714,53163.0,-8.881784e-16,91.04,42.08,77.288,57.632,53242.0,https://www.inaturalist.org/observations/12582...,https://inaturalist-open-data.s3.amazonaws.com...
37899,125854755,MtDiablo,20220711,2022,7,11,2022,10,38,Polypogon monspeliensis,...,55.425714,53163.0,-8.881784e-16,91.04,42.08,77.288,57.632,53242.0,https://www.inaturalist.org/observations/12585...,https://inaturalist-open-data.s3.amazonaws.com...
37900,127949771,MtDiablo,20220725,2022,7,25,2022,10,40,Holocarpha heermannii,...,66.431429,52542.0,-8.881784e-16,91.04,46.04,80.246,61.502,53201.0,https://www.inaturalist.org/observations/12794...,https://inaturalist-open-data.s3.amazonaws.com...

# 2. manually label observations for Adelinia grande

### 2a. export unlabeled data and label it

In [43]:
#reduce columns and export the test data for labeling
df_test_url_export = df_test[['id', 'park', 'plain_dates', 'genus_species', 'url', 'image_url']]

#export csv for manually checking observation URLs for bloom or not in bloom
df_test_url_export.to_csv('/Users/sandidge/Desktop/df_test_url_export.csv')

### 2b. select data for species of interest

In [20]:
df = df_test

#get observation counts for each species
spp_count = df.groupby(['genus_species'])['genus_species'].count().sort_values(ascending=False).reset_index(name='count')
print(spp_count.head(16))

               genus_species  count
0     Pedicularis densiflora    356
1    Ericameria linearifolia    314
2   Eriodictyon californicum    287
3       Calochortus venustus    274
4      Papaver heterophyllum    270
5         Clematis lasiantha    265
6    Dipterostemon capitatus    255
7       Diplacus aurantiacus    248
8       Delphinium nudicaule    246
9             Triteleia laxa    246
10    Collinsia heterophylla    239
11       Primula hendersonii    227
12          Salvia mellifera    223
13        Erysimum capitatum    222
14          Ptelea crenulata    221
15           Adelinia grande    216

In [42]:
df = df[df['genus_species']== 'Adelinia grande']
df.head(3)

,id,park,plain_dates,Year,Month,Day,WY,wy_month,WY_weeknum,genus_species,...,MaxDayLen_prior14,sum_prec_prior30,MaxTemp_prior30,MinTemp_prior30,AvgMaxTemp_prior30,AvgMinTemp_prior30,MaxDayLen_prior30,url,image_url,status
18920,105112877,MtDiablo,20220116,2022,1,16,2022,4,15,Adelinia grande,...,35451.0,4.027559,64.94,28.94,50.942,39.782,35451.0,https://www.inaturalist.org/observations/10511...,https://inaturalist-open-data.s3.amazonaws.com...,0.0
18942,105457143,MtDiablo,20220122,2022,1,22,2022,4,15,Adelinia grande,...,36006.0,1.677165,64.94,28.94,52.772,41.648,36006.0,https://www.inaturalist.org/observations/10545...,https://inaturalist-open-data.s3.amazonaws.com...,0.0
18964,105883395,MtDiablo,20220130,2022,1,30,2022,4,16,Adelinia grande,...,36870.0,0.098425,64.94,33.08,57.206,44.834,36870.0,https://www.inaturalist.org/observations/10588...,https://inaturalist-open-data.s3.amazonaws.com...,1.0

### 2c. import labeled data (will be updated with more species labeled)
df_test_url_export ---> mtdiablo_test

In [45]:
#import phenology (climate+daylength+observations) data from GitHub:Floydworks
url = ('https://raw.githubusercontent.com/Floydworks/WildflowerFinder_Phenology_Tool/main/cleaned_data_files/test_mtdiablo_partially_labeled.csv')
download = requests.get(url).content
# Read the downloaded content and turn it into a pandas dataframe
test_data_labeled = pd.read_csv(io.StringIO(download.decode('utf-8')))
print('test_data_labeled:', test_data_labeled.shape)

#get only labeled observations
df_test_labeled = test_data_labeled[~test_data_labeled['status'].isnull()]
print(df_test_labeled.shape)
df_test_labeled.head()

df_test_labeled['genus_species'].unique()

test_data_labeled: (17848, 41)
(216, 41)

array(['Adelinia grande'], dtype=object)

### 2d. check labels and map labeled status onto the main dataframe

In [46]:
#check for additional unlabeled observations of species of interest
#list of observation id that are labeled
df_test_labeled_ids = list(df_test_labeled['id'].unique())
print('labeled data: ',len(df_test_labeled_ids))

#list of all ids in the current dataframe
df_ids = list(df['id'].unique())
print('all data: ',len(df_ids))

#just the rows of unlabeled observations
df_unlabeled = df[~df['id'].isin(df_test_labeled_ids)]

print('unlabeled data: ',len(df_unlabeled))
if len(df_test_labeled) == len(df_ids):
    print('\nNo new data to label!')

labeled data:  216
all data:  216
unlabeled data:  0

No new data to label!

In [47]:
#create dictionary of main observation ids and status, old dataset
id_status_dict_main = dict(zip(df_test_labeled['id'], df_test_labeled['status']))
print(len(id_status_dict_main))

#map new labels onto phenology dataset
df['status'] = df['id'].map(id_status_dict_main)
#print(df.shape)

#check for remaining missing labels
#print('There are: ',df['status'].isna().sum(), '  missing status labels in the dataset')
#df.head()

216

In [48]:
df.head()

,id,park,plain_dates,Year,Month,Day,WY,wy_month,WY_weeknum,genus_species,...,MaxDayLen_prior14,sum_prec_prior30,MaxTemp_prior30,MinTemp_prior30,AvgMaxTemp_prior30,AvgMinTemp_prior30,MaxDayLen_prior30,url,image_url,status
18920,105112877,MtDiablo,20220116,2022,1,16,2022,4,15,Adelinia grande,...,35451.0,4.027559e+00,64.94,28.94,50.942,39.782,35451.0,https://www.inaturalist.org/observations/10511...,https://inaturalist-open-data.s3.amazonaws.com...,0.0
18942,105457143,MtDiablo,20220122,2022,1,22,2022,4,15,Adelinia grande,...,36006.0,1.677165e+00,64.94,28.94,52.772,41.648,36006.0,https://www.inaturalist.org/observations/10545...,https://inaturalist-open-data.s3.amazonaws.com...,0.0
18964,105883395,MtDiablo,20220130,2022,1,30,2022,4,16,Adelinia grande,...,36870.0,9.842520e-02,64.94,33.08,57.206,44.834,36870.0,https://www.inaturalist.org/observations/10588...,https://inaturalist-open-data.s3.amazonaws.com...,1.0
18984,107786294,MtDiablo,20220130,2022,1,30,2022,4,16,Adelinia grande,...,36870.0,9.842520e-02,64.94,33.08,57.206,44.834,36870.0,https://www.inaturalist.org/observations/10778...,https://inaturalist-open-data.s3.amazonaws.com...,1.0
19000,106265580,MtDiablo,20220206,2022,2,6,2022,5,17,Adelinia grande,...,37719.0,-8.881784e-16,64.94,39.02,58.508,45.524,37719.0,https://www.inaturalist.org/observations/10626...,https://static.inaturalist.org/photos/17848435...,1.0

In [40]:
df.columns

Index(['id', 'park', 'plain_dates', 'Year', 'Month', 'Day', 'WY', 'wy_month',
       'WY_weeknum', 'genus_species', 'genus', 'species', 'latitude',
       'longitude', 'prec_daily', 'prec_cum_WY', 'MonSumPrec', 'WkSumPrec',
       'minTemp', 'maxTemp', 'hour_rise', 'minute_rise', 'hour_set',
       'minute_set', 'day_length', 'sum_prec_prior14', 'MaxTemp_prior14',
       'MinTemp_prior14', 'AvgMaxTemp_prior14', 'AvgMinTemp_prior14',
       'MaxDayLen_prior14', 'sum_prec_prior30', 'MaxTemp_prior30',
       'MinTemp_prior30', 'AvgMaxTemp_prior30', 'AvgMinTemp_prior30',
       'MaxDayLen_prior30', 'url', 'image_url', 'status'],
      dtype='object')

### export test data for modeling

In [41]:
#export csv for use in modeling workbook
df.to_csv('YOUR FILE PATH')